"""Approval workflow management.

Handles the lifecycle of approval requests: creation, resolution,
and escalation deadline checks.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from enum import Enum
from typing import Any

import structlog

from rupiv.policy.rules import PolicyResult

log: structlog.stdlib.BoundLogger = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# State machine
# ---------------------------------------------------------------------------


class ApprovalState(str, Enum):
    """Approval request lifecycle states."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    ESCALATED = "escalated"
    AUTO_APPROVED = "auto_approved"


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class ApprovalRequest:
    """An approval request generated by the policy engine."""

    id: uuid.UUID
    rule_name: str
    trigger: str
    context_summary: dict[str, Any]
    approver: str
    state: ApprovalState
    created_at: datetime
    resolved_at: datetime | None = None
    escalation_deadline: datetime | None = None


# ---------------------------------------------------------------------------
# Approval lifecycle functions
# ---------------------------------------------------------------------------


def create_approval_request(
    rule_result: PolicyResult,
    context: dict[str, Any],
    *,
    escalation_after_hours: int | None = None,
) -> ApprovalRequest:
    """Create an ``ApprovalRequest`` from a policy evaluation result.

    If *escalation_after_hours* is provided, sets an escalation deadline.
    """
    now = datetime.now(UTC)

    escalation_deadline: datetime | None = None
    if escalation_after_hours is not None:
        escalation_deadline = now + timedelta(hours=escalation_after_hours)

    # Build a summary of the context (avoid storing full payload)
    context_summary: dict[str, Any] = {}
    for key, value in context.items():
        if isinstance(value, dict):
            # Keep top-level keys from nested dicts
            context_summary[key] = {
                k: v for k, v in value.items() if not isinstance(v, (dict, list))
            }
        elif not isinstance(value, (list, set)):
            context_summary[key] = value

    request = ApprovalRequest(
        id=uuid.uuid4(),
        rule_name=rule_result.rule_name,
        trigger=rule_result.reason or "",
        context_summary=context_summary,
        approver=rule_result.approver or "unassigned",
        state=ApprovalState.PENDING,
        created_at=now,
        escalation_deadline=escalation_deadline,
    )

    log.info(
        "policy.approval.created",
        request_id=str(request.id),
        rule_name=request.rule_name,
        approver=request.approver,
        escalation_deadline=str(escalation_deadline) if escalation_deadline else None,
    )

    return request


def resolve_approval(
    request: ApprovalRequest,
    decision: str,
    resolved_by: str,
) -> ApprovalRequest:
    """Resolve a pending approval request.

    Args:
        request: The approval request to resolve.
        decision: ``"approved"`` or ``"rejected"``.
        resolved_by: The identity of the person/system resolving.

    Returns:
        A new ``ApprovalRequest`` with updated state and resolved_at.

    Raises:
        ValueError: If the request is not in PENDING state or decision
            is invalid.
    """
    if request.state != ApprovalState.PENDING:
        raise ValueError(
            f"Cannot resolve request in state '{request.state.value}'; "
            f"expected '{ApprovalState.PENDING.value}'",
        )

    valid_decisions = {"approved", "rejected"}
    if decision not in valid_decisions:
        raise ValueError(f"Invalid decision '{decision}'; must be one of {valid_decisions}")

    new_state = ApprovalState(decision)
    now = datetime.now(UTC)

    resolved = ApprovalRequest(
        id=request.id,
        rule_name=request.rule_name,
        trigger=request.trigger,
        context_summary=request.context_summary,
        approver=request.approver,
        state=new_state,
        created_at=request.created_at,
        resolved_at=now,
        escalation_deadline=request.escalation_deadline,
    )

    log.info(
        "policy.approval.resolved",
        request_id=str(resolved.id),
        decision=decision,
        resolved_by=resolved_by,
    )

    return resolved


def check_escalation(request: ApprovalRequest) -> bool:
    """Check whether an approval request is past its escalation deadline.

    Returns ``True`` if the request is still PENDING and the current time
    exceeds the escalation deadline.  Returns ``False`` if there is no
    deadline or the request has already been resolved.
    """
    if request.state != ApprovalState.PENDING:
        return False

    if request.escalation_deadline is None:
        return False

    now = datetime.now(UTC)
    return now > request.escalation_deadline
