"""PDF invoice generation using fpdf2.

Generates professional-looking invoices with EU VAT compliance:
- Company header + invoice number
- Customer details + VAT number
- Line items table
- Tax breakdown with reverse charge notation when applicable
- Payment terms
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any

import structlog
from fpdf import FPDF

from rupiv.models.invoice import Invoice

log: structlog.stdlib.BoundLogger = structlog.get_logger(__name__)


def generate_invoice_pdf(
    invoice: Invoice,
    company_name: str = "Rupiv.ai BV",
    company_address: str = "Amsterdam, Netherlands",
    company_vat: str = "NL123456789B01",
) -> bytes:
    """Generate a PDF for the given invoice.

    Args:
        invoice: The Invoice ORM object (with ``line_items`` loaded).
        company_name: Issuing company name.
        company_address: Issuing company address.
        company_vat: Issuing company VAT number.

    Returns:
        PDF file contents as bytes.
    """
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # -- Header --
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 10, company_name, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 5, company_address, ln=True)
    pdf.cell(0, 5, f"VAT: {company_vat}", ln=True)
    pdf.ln(10)

    # -- Invoice details --
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 8, f"Invoice {invoice.invoice_number}", ln=True)
    pdf.set_font("Helvetica", "", 10)

    pdf.cell(95, 5, f"Date: {invoice.created_at.strftime('%Y-%m-%d')}")
    pdf.cell(95, 5, f"Due: {invoice.due_date.isoformat()}", ln=True)

    pdf.cell(95, 5, f"Period: {invoice.period_start.strftime('%Y-%m-%d')} to {invoice.period_end.strftime('%Y-%m-%d')}")
    pdf.cell(95, 5, f"Currency: {invoice.currency}", ln=True)

    # Customer info
    if hasattr(invoice, "customer") and invoice.customer:
        customer = invoice.customer
        pdf.ln(5)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 5, "Bill To:", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 5, customer.name, ln=True)
        pdf.cell(0, 5, customer.email, ln=True)
        if customer.vat_number:
            pdf.cell(0, 5, f"VAT: {customer.vat_number}", ln=True)

    pdf.ln(10)

    # -- Line items table --
    pdf.set_font("Helvetica", "B", 9)
    col_widths = [80, 25, 30, 30, 25]
    headers = ["Description", "Qty", "Unit Price", "Amount", "Model"]

    for w, h in zip(col_widths, headers):
        pdf.cell(w, 7, h, border=1)
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    line_items = invoice.line_items if hasattr(invoice, "line_items") else []
    for li in line_items:
        desc = li.description or ""
        qty = str(Decimal(str(li.quantity)).quantize(Decimal("0.01")))
        unit = str(Decimal(str(li.unit_amount)).quantize(Decimal("0.0001")))
        amt = str(Decimal(str(li.amount)).quantize(Decimal("0.01")))
        model = getattr(li, "pricing_model", "") or ""

        pdf.cell(col_widths[0], 6, desc[:45], border=1)
        pdf.cell(col_widths[1], 6, qty, border=1, align="R")
        pdf.cell(col_widths[2], 6, unit, border=1, align="R")
        pdf.cell(col_widths[3], 6, amt, border=1, align="R")
        pdf.cell(col_widths[4], 6, str(model), border=1)
        pdf.ln()

    pdf.ln(5)

    # -- Totals --
    pdf.set_font("Helvetica", "", 10)
    subtotal = Decimal(str(invoice.subtotal)).quantize(Decimal("0.01"))
    tax = Decimal(str(invoice.tax_amount)).quantize(Decimal("0.01"))
    total = Decimal(str(invoice.total)).quantize(Decimal("0.01"))

    pdf.cell(135, 6, "Subtotal:", align="R")
    pdf.cell(55, 6, f"{invoice.currency} {subtotal}", align="R", ln=True)

    tax_label = "VAT"
    if hasattr(invoice, "tax_type") and invoice.tax_type == "reverse_charge":
        tax_label = "VAT (Reverse Charge)"
    if invoice.tax_rate:
        tax_label += f" ({Decimal(str(invoice.tax_rate)) * 100:.1f}%)"

    pdf.cell(135, 6, f"{tax_label}:", align="R")
    pdf.cell(55, 6, f"{invoice.currency} {tax}", align="R", ln=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(135, 8, "Total:", align="R")
    pdf.cell(55, 8, f"{invoice.currency} {total}", align="R", ln=True)

    # -- Reverse charge notice --
    if hasattr(invoice, "tax_type") and invoice.tax_type == "reverse_charge":
        pdf.ln(5)
        pdf.set_font("Helvetica", "I", 8)
        pdf.cell(
            0, 5,
            "VAT reverse charge: The recipient is liable for VAT under Article 196 of EU Directive 2006/112/EC.",
            ln=True,
        )

    # -- Footer --
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 4, f"Generated by {company_name} - Outcome-based billing infrastructure", ln=True)
    pdf.cell(0, 4, f"Invoice ID: {invoice.id}", ln=True)

    log.info("invoice_pdf_generated", invoice_id=str(invoice.id))

    return pdf.output()
